cart/urls.py
from django.urls import path
from . import views
# from .views import OrderCreate

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),
    # path('checkout/', OrderCreate.as_view(), name='checkout'),
]

shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from user import views as user_views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    path('login/', auth_views.LoginView
         .as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
    path('register/', user_views.register, name='register-users'),
    path('cart/', include('cart.urls'), name='cart'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

mainapp/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.urls import reverse
User = get_user_model()


def get_models_for_count(*model_names):
    return [models.Count(model_name) for model_name in model_names]


def get_product_url(obj, viewname):
    ct_model = obj.__class__._meta.model_name
    return reverse(viewname, kwargs={'ct_model': ct_model, 'slug': obj.slug})


class LatestProductsManager:
    @staticmethod
    def get_products_for_main_page(*args, **kwargs):
        with_respect_to = kwargs.get('with_respect_to')
        products = []
        ct_models = ContentType.objects.filter(model__in=args)
        for ct_model in ct_models:
            model_products = ct_model.model_class()._base_manager.all().order_by('-id')[:5]
            products.extend(model_products)
        if with_respect_to:
            ct_model = ContentType.objects.filter(model=with_respect_to)
            if ct_model.exists():
                if with_respect_to in args:
                    return sorted(products, key=lambda x: x.__class__._meta.model_name.startswith(with_respect_to), reverse=True)
        return products


class LatestProducts:
    objects = LatestProductsManager()


class CategoryManager(models.Manager):
    CATEGORY_NAME_COUNT_NAME = {
        'Ноутбуки': 'notebook__count',
       'Смартфоны': 'smartphone__count'
    }

    def get_queryset(self):
        return super().get_queryset()

    def get_categories_for_nav(self):
        models = get_models_for_count('notebook', 'smartphone')
        qs = list(self.get_queryset().annotate(*models))
        data = [
            dict(name=c.name, url=c.get_absolute_url(), count=getattr(c, self.CATEGORY_NAME_COUNT_NAME[c.name]))
            for c in qs
        ]
        return data


class Category(models.Model):
    name = models.CharField(max_length=255, verbose_name='Имя категории')
    slug = models.SlugField(unique=True)

    objects = CategoryManager()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'slug': self.slug})


class Product(models.Model):
    class Meta:
        abstract = True

    category = models.ForeignKey(Category, verbose_name='Категория', on_delete=models.CASCADE)
    title = models.CharField(max_length=50, verbose_name='Наименование')
    slug = models.SlugField(unique=True)
    image = models.ImageField(verbose_name='Изображение')
    description = models.TextField(verbose_name='Описание', null=True)
    price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Цена')

    def __str__(self):
        return self.title


class Notebook(Product):
    diagonal = models.CharField(max_length=255, verbose_name='Диагональ')
    display = models.CharField(max_length=255, verbose_name='Тип дисплея')
    processor_freq = models.CharField(max_length=255, verbose_name='Частота процессора')
    ram = models.CharField(max_length=255, verbose_name='Оперативная память')
    video_cart = models.CharField(max_length=255, verbose_name='Видеокарта')
    time_without_charge = models.CharField(max_length=255, verbose_name='Время работы аккумулятора')

    def __str__(self):
        return f'{self.category.name}: {self.title}'

    def get_absolute_url(self):
        return get_product_url(self, 'product_detail')


class Smartphone(Product):
    diagonal = models.CharField(max_length=255, verbose_name='Диагональ')
    display = models.CharField(max_length=255, verbose_name='Тип дисплея')
    resolution = models.CharField(max_length=255, verbose_name='Разрешение экрана')
    accum_volume = models.CharField(max_length=255, verbose_name='Объем батареи')
    ram = models.CharField(max_length=255, verbose_name='Оперативная память')
    sd = models.BooleanField(default=True, verbose_name='Наличие SD карты')
    sd_volume_max = models.CharField(max_length=255, null=True, blank=True,
                                     verbose_name='Максимальный объем встраиваемой карты')
    main_cam_mp = models.CharField(max_length=255, verbose_name='Главная камера')
    frontal_cam_mp = models.CharField(max_length=255, verbose_name='Фронтальная камера')

    def __str__(self):
        return f'{self.category.name}: {self.title}'

    def get_absolute_url(self):
        return get_product_url(self, 'product_detail')

    # @property
    # def sd(self):
    #     if self.sd:
    #         return 'Да'
    #     return 'Нет'


# class CartProduct(models.Model):
#     user = models.ForeignKey(User, verbose_name='Покупатель', on_delete=models.CASCADE)
#     cart = models.ForeignKey('Cart', verbose_name='Корзина', on_delete=models.CASCADE, related_name='related_products')
#     content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
#     object_id = models.PositiveIntegerField()
#     content_object = GenericForeignKey('content_type', 'object_id')
#     quantity = models.PositiveIntegerField(default=1)
#     total_price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Общая цена')
#
#     def __str__(self):
#         return f'Продукт: {self.content_object.title}'


# class Cart(models.Model):
#     owner = models.ForeignKey(User, verbose_name='Владелец', on_delete=models.CASCADE)
#     products = models.ManyToManyField(CartProduct, blank=True, related_name='related_cart')
#     total_products = models.PositiveIntegerField(default=0)
#     final_price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Общая цена')
#     in_order = models.BooleanField(default=False)
#     for_anonymous_user = models.BooleanField(default=False)
#
#     def __str__(self):
#         return str(self.id)


# class Customer(models.Model):
#     user = models.ForeignKey(User, verbose_name='Пользователь', on_delete=models.CASCADE)
#     phone = models.CharField(max_length=20, verbose_name='Номер телефона')
#     address = models.CharField(max_length=255, verbose_name='Адрес')
#
#     def __str__(self):
#         return f'Покупатель: {self.user.username}'

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from mainapp.models import Smartphone
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Smartphone, id=product_id)
    form = CartAddP+-roductForm(request.POST)
    if form.is_valid():
        print('aaaaaaaa')
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart')


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart.html', {'cart': cart})

templates/admin.html
{% extends 'admin/change_form.html' %}
{% load static %}

{% block admin_change_form_document_ready %}
{{ block.super }}
<script>
(function($) {
    $('#id_sd').on('click', function(){
        if($('#id_sd').prop('checked') == true){
            $('#id_sd_volume_max').prop('readonly', false)
            $('#id_sd_volume_max').val('')
            $('#id_sd_volume_max').css('background', 'white')
        }else{
            $('#id_sd_volume_max').prop('readonly', true)
            $('#id_sd_volume_max').val('')
            $('#id_sd_volume_max').css('background', 'lightgrey')
        }
    })

})(django.jQuery);
</script>
{% endblock %}

templates/cart.html
{% extends "index.html" %}
{% load static %}

    Your shopping cart
{% block content %}
    <h1>Your shopping cart</h1>
    <table class="cart">
        <thead>
        <tr>
            <th>Image</th>
            <th>Product</th>
            <th>Quantity</th>
            <th>Remove</th>
            <th>Unit price</th>
            <th>Price</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
                <tr>
                    <td>
                        <a href="{{ product.get_absolute_url }}">
                            <img src="
                                {% if product.image %}
                                    {{ product.image.url }}
                                {% else %}
                                    {% static 'media/no_image.png' %}
                                {% endif %}">
                        </a>
                    </td>
                    <td>{{ item.name }}</td>
                    <td>{{ item.quantity }}</td>
                    <td><a href="{% url 'cart_remove' product.id%}">Remove</a></td>
                    <td class="num">${{ item.price }}</td>
                    <td class="num">${{ item.total_price }}</td>
                </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Total</td>
            <td colspan="4"></td>
            <td class="num">${{ cart.get_total_price }}</td>
        </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href="{% url 'base' %}" class="button light">Continue shopping</a>
        <a href="#" class="button">Checkout</a>
    </p>
{% endblock %}

templates/category.html
{% extends 'index.html' %}

{% block content %}

{{ category.name }}

{% endblock content%}

templates/index.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />

  <title>Shopy</title>

  <!-- slider stylesheet -->
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.1.3/assets/owl.carouses/jqul.min.css" />

  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />

  <!-- fonts style -->
  <link href="https://fonts.googleapis.com/css?family=Dosis:400,500|Poppins:400,700&display=swap" rel="stylesheet">
  <!-- Custom styles for this template -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet" />
  <link href="/static/css/style.css" rel="stylesheet" />
  <!-- responsive style -->
  <link href="{% static 'css/responsive.css' %}" rel="stylesheet" />
</head>

<body>
  <div class="hero_area">
    <!-- header section starts -->
    <header class="header_section">
      <div class="container-fluid">
        <nav class="navbar navbar-expand-lg custom_nav-container pt-3">
          <a class="navbar-brand" href="{% url 'base' %}">
            <span>
              Shopy
            </span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <div class="d-flex ml-auto flex-column flex-lg-row align-items-center">
              <ul class="navbar-nav  ">
                {%if user.is_authenticated %}
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'cart' %}"> Корзина <span class="badge badge-pill badge-danger">0</span></a>
                </li>
                <li>
                  <a class="nav-link" href="{% url 'logout'%}">logout</a>
                </li>
                {% endif %}
                {% if not user.is_authenticated %}
                <li>
                  <a class="nav-link" href="{% url 'register-users'%}">register</a>
                </li>
                <li>
                  <a class="nav-link" href="{% url 'login'%}">login</a>
                </li>
                {% endif %}
                <li>
                  <a class="">{{ user.username }}</a>
                </li>

              </ul>
                <!--     Поиск   (лупа)  -->
<!--              <form class="form-inline my-2 my-lg-0 ml-0 ml-lg-4 mb-3 mb-lg-0">-->
<!--                <button class="btn  my-2 my-sm-0 nav_search-btn" type="submit"></button>-->
<!--              </form>-->
            </div>
          </div>
        </nav>
      </div>
    </header>
    <!-- end header section -->
    <!-- slider section -->
    {% block content %}

    <section class=" slider_section position-relative">

      <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">

        <div class="carousel-inner">
          <div class="carousel-item active">
            <div class="slider_item-box">
              <div class="slider_item-container">
                <div class="container">
                  <div class="row">
                    <div class="col-md-5">
                      <div class="slider_img-box">
                        <div>
                          <img src="media/phone.png" alt="" class="" />
                        </div>
                      </div>
                    </div>
                    <div class="col-md-7">
                      <div class="slider_item-detail">
                        <div>
                          <h1>
                            Stylish Smartphones
                          </h1>
                          <p>
                            Welcome :)
                          </p>
                          <div class="d-flex">
                            <a href="" class="slider-btn1 mr-3">
                              Read More
                            </a>
                            <a href="" class="slider-btn2">
                              Contact Us
                            </a>
                          </div>
                        </div>
                      </div>
                    </div>

                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="carousel-item">
            <div class="slider_item-box">
              <div class="slider_item-container">
                <div class="container">
                  <div class="row">
                    <div class="col-md-5">
                      <div class="slider_img-box">
                        <div>
                          <img src="media/iphone-13-pink-select-2021.png" alt="" class="" />
                        </div>
                      </div>
                    </div>
                    <div class="col-md-7">
                      <div class="slider_item-detail">
                        <div>
                          <h1>
                            Stylish Smartphones
                          </h1>
                          <p>
                            iPhone 13 and iPhone 13 mini are designed with the following features to reduce their environmental impact
                          </p>
                          <div class="d-flex">
                            <a href="" class="slider-btn1 mr-3">
                              Read More
                            </a>
                            <a href="" class="slider-btn2">
                              Contact Us
                            </a>
                          </div>
                        </div>
                      </div>
                    </div>

                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="carousel-item">
            <div class="slider_item-box">
              <div class="slider_item-container">
                <div class="container">
                  <div class="row">
                    <div class="col-md-5">
                      <div class="slider_img-box">
                        <div>
                          <img src="media/macbook.png" alt="" class="" />
                        </div>
                      </div>
                    </div>
                    <div class="col-md-7">
                      <div class="slider_item-detail">
                        <div>
                          <h1 class="">
                            Stylish notebooks
                          </h1>
                          <p>
                            "MacBook" is a term used for a brand of Mac notebook computers that Apple started producing in 2006. The American multinational corporation created MacBook computers when it consolidated its PowerBook and iBook lines during its transition to Intel processor-based products.
                          </p>
                          <div class="d-flex">
                            <a href="" class="slider-btn1 mr-3">
                              Read More
                            </a>
                            <a href="" class="slider-btn2">
                              Contact Us
                            </a>
                          </div>
                        </div>
                      </div>
                    </div>

                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="custom_carousel-control">
          <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>
    </section>
    <!-- end slider section -->
  </div>


  <div class="container">

    <div class="row ">

      <div class="col-md-2 mt-5">
        <div class="list-group">
          {% for category in categories %}
          <a href="{{ category.url }}" class="list-group-item">{{ category.name }} ({{ category.count }})</a>
          {% endfor %}
        </div>

      </div>
      <!-- /.col-lg-3 -->





      <section class="col-md-10 py-6">
<!--    row-->
            <div class="container px-4 px-lg-5 mt-5">
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                  {% for product in products %}
                    <div class="col mb-5">
                        <div class="card h-100">
                          <a href="{{ product.get_absolute_url }}"><img class="card-img-top" src="{{ product.image.url }}" alt=""></a>
                            <!-- Product image-->
<!--                            <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." />-->
                            <!-- Product details-->
                          <div class="card-body p-4">
                                <div class="text-center">
                                  <h4 class="card-title">
                                    <a href="{{ product.get_absolute_url }}">{{ product.title }}</a>
                                  </h4>
                                  <h5 class="fw-bolder">{{ product.price }} сом</h5>
                                </div>
                          </div>
                        </div>
                    </div>
                  {% endfor %}
                </div>
            </div>
  </section>
    <!-- about section -->



  {% endblock content %}

  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
  </div>
             </div>

  <section class="footer_section">
    <p>
      © 2020 All Rights Reserved By
      <a href="https://html.design/">Free Html Templates</a>
    </p>
  </section>

</body>

</html>

templates/login.html
{% extends "index.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <form method="POST" class="col-12 col-md-6 pl-3 pr-3 pl-md-0 pr-md-0">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="mb-3 white-important">
                Login
            </legend>
            {{ form | crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-primary" type="submit">Login</button>
        </div>
    </form>
    <div class="pt-3">
        <small class="text-muted">
            Do you need an account? <a class="ml-2" href="{% url 'register-users' %}">Sign up</a>
        </small>
    </div>
</div>
{% endblock content %}

templates/logout.html
{% extends "index.html" %}
{% block content %}
<div class="container">
    <h3 class="white-important">You've been logged out</h3>
    <div class="pt-3">
        <small class="text-muted">
            Login again? <a class="ml-2" href="{% url 'login' %}">Login</a>
        </small>
    </div>
</div>
{% endblock content %}

templates/notebook_create.html
{% extend 'index.html' %}

{% load static %}
{% block content %}


{% endblock content %}

templates/notebook_specification.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<table class="table">
  <tbody>
    <tr>
      <td>Диагональ</td>
      <td>{{ product.diagonal }}</td>
    </tr>
    <tr>
      <td>Тип дисплея</td>
      <td>{{ product.display }}</td>
    </tr>
    <tr>
      <td>Частота процессора</td>
      <td>{{ product.processor_freq }}</td>
    </tr>
    <tr>
      <td>Оперативная память</td>
      <td>{{ product.ram }}</td>
    </tr>
    <tr>
      <td>Видео карта</td>
      <td>{{ product.video_cart }}</td>
    </tr>
    <tr>
      <td>Время без зарядки</td>
      <td>{{ product.time_without_charge }}</td>
    </tr>
  </tbody>
</table>
</body>
</html>

templates/product_detail.html
{% extends 'index.html' %}
{% load static %}
{% block content %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'base' %}">Главная</a></li>
    <li class="breadcrumb-item"><a href="#">{{ product.category.name }}</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{ product.title }}</li>
  </ol>
</nav>
<div class="row">
    <div class="col-md-6">
        <img src="{{ product.image.url }}" class="img-fluid">
    </div>
    <div class="cl-ng-8">
        <h3>{{ product.title }}</h3>
        <p>Цена: {{ product.price }} сом</p>
        <p>Описание: {{ product.description }}</p>

    </div>
    <div class="cl-ng-8">
        <p>Характеристики: </p>
        {{ product.category.slug }}
        {% if product.category.slug == 'notebooks' %}
            {% include 'notebook_specification.html' %}
        {% else %}
            {% include 'smartphone_specification.html' %}
        {% endif %}
        <form action="{% url 'cart:cart_add' product.id %}" method="post" style="margin-bottom: 30px; font-size: 30px;">
        {{ cart_product_form }}
        {% csrf_token %}
        <input type="submit" value="В корзину">

    </form>
    </div>
</div>


{% endblock content %}

templates/register.html
{% extends "index.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <form method="POST" class="col-12 col-md-6 pl-3 pr-3 pl-md-0 pr-md-0">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="mb-3 white-important">
                Register a new account
            </legend>
            {{ form | crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-primary" type="submit">Sign Up</button>
        </div>
    </form>
    <div class="pt-3">
        <small class="text-muted">
            Already Have An Account? <a class="ml-2" href="{% url 'login' %}">Sign In</a>
        </small>
    </div>
</div>
{% endblock content %}

templates/smartphone_specification.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<table class="table">
  <tbody>
    <tr>
      <td>Диагональ</td>
      <td>{{ product.diagonal }}</td>
    </tr>
    <tr>
      <td>Тип дисплея</td>
      <td>{{ product.display }}</td>
    </tr>
    <tr>
      <td>Разрешение экрана</td>
      <td>{{ product.resolution}}</td>
    </tr>
    <tr>
      <td>Заряд аккумулятора</td>
      <td>{{ product.accum_volume}}</td>
    </tr>
    <tr>
      <td>Оперативная память</td>
      <td>{{ product.ram}}</td>
    </tr>
    <tr>
      <td>Наличие слота для SD карты</td>
      <td>{{ product.sd }}</td>
    </tr>
    <tr>
      <td>Максимальный объем SD карты</td>
      <td>{{ product.sd_volume_max }}</td>
    </tr>
    <tr>
      <td>Камера (МП)</td>
      <td>{{ product.main_cam_mp }}</td>
    </tr>
    <tr>
      <td>Фронтальная камера (МП)</td>
      <td>{{ product.frontal_cam_mp }}</td>
    </tr>
  </tbody>
</table>
</body>
</html>